apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: phpredisadmin
  name: phpredisadmin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: phpredisadmin
    spec:
      containers:
      - env:
        - name: PHPREDMIN_DATABASE_REDIS_0_HOST
          value: redishost
        image: faktiva/php-redis-admin
        name: phpredisadmin
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
