apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: phpredisadmin
  name: phpredisadmin
spec:
  ports:
  - name: "8086"
    port: 8086
    targetPort: 80
  selector:
    io.kompose.service: phpredisadmin
status:
  loadBalancer: {}
