apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: redishost
  name: redishost
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redishost
    spec:
      containers:
      - image: redis:alpine
        name: redishost
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}
