apiVersion: v1
data:
  GUZABAPLATFORM_PLATFORM_APPLICATION_MYSQLCONNECTION_DATABASE: guzaba2
  GUZABAPLATFORM_PLATFORM_APPLICATION_MYSQLCONNECTION_HOST: mysqlhost
  GUZABAPLATFORM_PLATFORM_APPLICATION_MYSQLCONNECTION_PASSWORD: somerootpass
  GUZABAPLATFORM_PLATFORM_APPLICATION_MYSQLCONNECTION_PORT: "3306"
  GUZABAPLATFORM_PLATFORM_APPLICATION_MYSQLCONNECTION_TPREFIX: guzaba_
  GUZABAPLATFORM_PLATFORM_APPLICATION_MYSQLCONNECTION_USER: root
  GUZABAPLATFORM_PLATFORM_APPLICATION_MYSQLCONNECTIONCOROUTINE_DATABASE: guzaba2
  GUZABAPLATFORM_PLATFORM_APPLICATION_MYSQLCONNECTIONCOROUTINE_HOST: mysqlhost
  GUZABAPLATFORM_PLATFORM_APPLICATION_MYSQLCONNECTIONCOROUTINE_PASSWORD: somerootpass
  GUZABAPLATFORM_PLATFORM_APPLICATION_MYSQLCONNECTIONCOROUTINE_PORT: "3306"
  GUZABAPLATFORM_PLATFORM_APPLICATION_MYSQLCONNECTIONCOROUTINE_TPREFIX: guzaba_
  GUZABAPLATFORM_PLATFORM_APPLICATION_MYSQLCONNECTIONCOROUTINE_USER: root
  GUZABAPLATFORM_PLATFORM_APPLICATION_REDISCONNECTION_DATABASE: "0"
  GUZABAPLATFORM_PLATFORM_APPLICATION_REDISCONNECTION_HOST: redishost
  GUZABAPLATFORM_PLATFORM_APPLICATION_REDISCONNECTION_PASSWORD: ""
  GUZABAPLATFORM_PLATFORM_APPLICATION_REDISCONNECTION_PORT: "6379"
  GUZABAPLATFORM_PLATFORM_APPLICATION_REDISCONNECTION_TIMEOUT: "1.5"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: swoole-guzaba-platform-env
  name: swoole-guzaba-platform-env
